
_target_: verl.workers.config.FSDPEngineConfig


wrap_policy:


  min_num_params: 0



param_offload: false



optimizer_offload: false


offload_policy: false


reshard_after_forward: true


fsdp_size: -1



forward_prefetch: False


model_dtype: fp32


use_orig_params: false


ulysses_sequence_parallel_size: 1


entropy_from_logits_with_chunking: false


use_torch_compile: true


entropy_checkpointing: false


forward_only: false


strategy: fsdp
