
strategy: ${actor_rollout_ref.actor.strategy}



use_torch_compile: ${oc.select:actor_rollout_ref.actor.use_torch_compile,true}



log_prob_micro_batch_size: null


log_prob_micro_batch_size_per_gpu: null



log_prob_use_dynamic_bsz: ${oc.select:actor_rollout_ref.actor.use_dynamic_bsz,false}



log_prob_max_token_len_per_gpu: ${oc.select:actor_rollout_ref.actor.ppo_max_token_len_per_gpu,16384}


profiler:


  _target_: verl.utils.profiler.ProfilerConfig


  tool: ${oc.select:global_profiler.tool,null}


  enable: False


  all_ranks: False


  ranks: []


  save_path: ${oc.select:global_profiler.save_path,null}


  tool_config:


    nsys:


      _target_: verl.utils.profiler.config.NsightToolConfig
    

      discrete: ${oc.select:global_profiler.global_tool_config.nsys.discrete}
    

    npu:


      _target_: verl.utils.profiler.config.NPUToolConfig



      contents: []


      level: "level1"


      analysis: True


      discrete: False
    

    torch:


      _target_: verl.utils.profiler.config.TorchProfilerToolConfig




      step_start: 0


      step_end: null


    torch_memory:


      _target_: verl.utils.profiler.config.TorchMemoryToolConfig


      trace_alloc_max_entries: ${oc.select:global_profiler.global_tool_config.torch_memory.trace_alloc_max_entries,100000}


      stack_depth: ${oc.select:global_profiler.global_tool_config.torch_memory.stack_depth,32}