






defaults:


  - reward_model


  - _self_

strategy: fsdp

model:


  use_shm: False


  use_remove_padding: False


  use_fused_kernels: ${actor_rollout_ref.model.use_fused_kernels}


  fsdp_config:


    _target_: verl.workers.config.FSDPEngineConfig


    wrap_policy:


      min_num_params: 0


    param_offload: False


    reshard_after_forward: True


    fsdp_size: -1



    forward_prefetch: False


ulysses_sequence_parallel_size: 1